name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  introduction_screen: ^3.1.4
  ar_flutter_plugin_2: ^0.0.3
  flutter_compass: ^0.8.1
  geolocator: ^12.0.0
  google_maps_flutter: ^2.14.0
  permission_handler: ^11.4.0
  vector_math: ^2.2.0
  flutter_polyline_points: ^3.1.0
  audioplayers: ^6.5.1
  flutter_dotenv: ^6.0.0
  just_audio: ^0.10.5
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/voices/
